### ISSUE TITLE
Not updating serial for DNS zones

### ISSUE THREAD

**Issue by mixMugz** [gclayburg/synology-diskstation-scripts#11]
Script work fine except updating serial for DNS zone.
As a result - zone not updating at secondary dns server

**Comment by gclayburg** [comment]
Right, I noticed this a while ago but I'm only running a single server.  If this were fixed, would you be able to test it? @mixMugz   Or better yet, could you suggest a fix??

**Comment by mixMugz** [comment]
Yeo. No problem. But every time when making zone changes make serial +1. For best practice use serial like: yyyymmddxx where yyyy - current year, mm - month, dd - day, xx - changes in a day from 01 to 99

**Comment by gclayburg** [comment]
pull requests are welcome for anyone experiencing this issue.  I can help test a fix, but since I don't use a DNS slave this issue is a low priority.

**Comment by gclayburg** [comment]
Nevermind, I ended up fixing this issue myself.  @mixMugz  could you test it?

**Comment by mixMugz** [comment]
@gclayburg Ok. I will test

**Comment by mixMugz** [comment]
Seems work. Need more stress test ;)

**Comment by gclayburg** [comment]
AFAIK, this issue is resolved.  Please open a new issue if the problem still exists.
