### ISSUE TITLE
Synology S99pollDHCP.sh not working on DSM 6.0.1

### ISSUE THREAD

**Issue by paulsep** [gclayburg/synology-diskstation-scripts#14]
While the ps command has been changed in DSM 6.0.1, you'll get an error, when checking, whether poll-dhcp-changes.sh is running or not.

**The lines in S99pollDHCP.sh should read:**
POLL_RUNNING=`ps x | grep poll-dhcp-changes | grep -v grep |wc -l`
MYPID=`ps x | grep poll-dhcp-changes | grep -v grep | awk -F' ' '{print $1}'`

**Same issue in startDHCP-DNS.sh. Should read:**
POLL_RUNNING=`ps x | grep poll-dhcp-changes | grep -v grep |wc -l`

**Comment by gclayburg** [comment]
Thanks for this report.  I'll incorporate these fixes soon.

**Comment by tonysurma** [comment]
Again thanks for this.  I think I have this fixed in PR in my fork without fuzzing the file with windows cruft.

**Comment by gclayburg** [comment]
@tonysurma   I just added a fix that should work on both DSM 5 and 6.  Do you mind testing it under DSM 6?  I don't have a DSM 6 box for testing.

**Comment by paulsep** [comment]
@gclayburg 
I guess you tried to send me the fix via email.
I'm sorry, but my mailserver does not accept any kind of script files, send by email, cause of potential viruses.
You have to compress the fix as zip or rar to send it to me by email.

Again, sorry for that.

**Comment by tonysurma** [comment]
@gclayburg I will test it on 6 this weekend.  Thanks

**Comment by gclayburg** [comment]
@paulsep   That must've been github being all inclusive when your issue is updated.  Everything relevant to this issue can be found in this repository and my recent commits.

**Comment by tonysurma** [comment]
FWIW 24 days later this is fixed in your repo - thanks!
