### ISSUE TITLE
Small problem when starting S99pollDHCP.sh

### ISSUE THREAD

**Issue by Zafrusteria** [gclayburg/synology-diskstation-scripts#5]
the script throws an error every time it is run after the first time when reying to recreate the directory /var/services/homes/admin. 

And the file that the out put is redirected into is a little unusual :-) it is currently set to 'pwd'. I have attached my file changes .
[S99pollDHCP_zaf.txt](https://github.com/gclayburg/synology-diskstation-scripts/files/147272/S99pollDHCP_zaf.txt)

In the documentation there is no mention of the new settings file. It still says to edit the file diskstation_dns_modify.sh.

Other than that great script and documentation, all works great!

Zafrusteria

**Comment by gclayburg** [comment]
You're right - the script does look odd.  Yours is much better. :-)   I just checked how I am using it and noticed this git repo is not up to date.  I'll update it in the next day or two and incorporate your suggestion.
