### ISSUE TITLE
Task Scheduler sample correction

### ISSUE THREAD

**Issue by gsmithx2** [gclayburg/synology-diskstation-scripts#6]
This is great stuff.  Thank you!  Only issue I had was that your example for starting the poll script via Task Scheduler is missing the "start" command.  It should be:

/usr/local/etc/rc.d/S99pollDHCP.sh start >>/var/services/homes/admin/startS99pollDHCP.log

**Comment by gclayburg** [comment]
Good catch!  I'll update the docs
