### ISSUE TITLE
/bin/ash: : No such file or directory

### ISSUE THREAD

**Issue by jollyshots** [gclayburg/synology-diskstation-scripts#8]
First, thanks for writing this!

Each time I run the startup I get the following error in the dhc-dns.log file
dhcp leases changed - reloading DNS
/bin/ash: 
: No such file or directory

/bin/ash does exist.

 And when I try to manually stop the services I get the following error
/usr/local/etc/rc.d/S99pollDHCP.sh: line 32: [: : integer expression expected

I'm running DSM 6.0-7321 Update 6 on a DS212J

**Comment by gclayburg** [comment]
Can you verify the file permissions and that you are running the scripts as root?

**Comment by gclayburg** [comment]
closed for lack of activity
