### ISSUE TITLE
Changing frequency and schedule

### ISSUE THREAD

**Issue by jollyshots** [gclayburg/synology-diskstation-scripts#9]
I was wondering how I could change the update to happen every hour and then only run during certain hours?  I would assume I could create a task to stop and start when I want and the frequency would be to change the poll-dhcp-changes.sh loop from 5 to 3600 for 1 hour?

**Comment by gclayburg** [comment]
I would think you should be able to do that with the DSM task scheduler.  Just run the diskstation_dns_modify.sh script directly.  You would want to remove or disable the S99pollDHCP.sh script and the poll-dhcp-changes.sh script.  Those only exist to force the diskstation_dns_modify.sh script to run automatically.
